# Generated by Django 5.2 on 2025-04-07 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='profile_icons/'),
        ),
    ]
