# Generated by Django 5.2 on 2025-04-08 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profile_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='daySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=50)),
                ('openTime', models.CharField(max_length=50)),
                ('closeTime', models.CharField(max_length=50)),
                ('dayOff', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('weight', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('contextRoot', models.CharField(max_length=50)),
                ('productionUrl', models.CharField(max_length=50)),
                ('lkEnabled', models.BooleanField()),
                ('shopEnabled', models.BooleanField()),
                ('shopDomainPilot', models.BooleanField()),
                ('defaultLanguage', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('locationType', models.CharField(max_length=50)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('cityId', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
                ('subwayStation', models.CharField(blank=True, max_length=50, null=True)),
                ('landmarks', models.CharField(blank=True, max_length=50, null=True)),
                ('salePointId', models.CharField(blank=True, max_length=50, null=True)),
                ('phoneNumberOrdering', models.CharField(blank=True, max_length=50, null=True)),
                ('mnpOrdering', models.CharField(blank=True, max_length=50, null=True)),
                ('deviceOrdering', models.CharField(blank=True, max_length=50, null=True)),
                ('esimOrdering', models.CharField(blank=True, max_length=50, null=True)),
                ('b2bShopAvailability', models.CharField(blank=True, max_length=50, null=True)),
                ('tele2Store', models.CharField(blank=True, max_length=50, null=True)),
                ('amountThreshold', models.CharField(blank=True, max_length=50, null=True)),
                ('externalLocationId', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('showcaseId', models.CharField(blank=True, max_length=50, null=True)),
                ('daySchedules', models.ManyToManyField(to='core.dayschedule')),
                ('services', models.ManyToManyField(to='core.service')),
                ('sites', models.ManyToManyField(to='core.site')),
            ],
        ),
    ]
