# Generated by Django 5.2 on 2025-04-08 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_dayschedule_service_site_office'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayschedule',
            name='closeTime',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dayschedule',
            name='openTime',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
