# Generated by Django 5.2 on 2025-04-09 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_cells'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayschedule',
            name='closeTime',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='dayschedule',
            name='day',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='dayschedule',
            name='openTime',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='office',
            name='address',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='office',
            name='amountThreshold',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='office',
            name='b2bShopAvailability',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='office',
            name='city',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='office',
            name='cityId',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='office',
            name='deviceOrdering',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='office',
            name='email',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='office',
            name='esimOrdering',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='office',
            name='externalLocationId',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='office',
            name='landmarks',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='office',
            name='locationType',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='office',
            name='mnpOrdering',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='office',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='office',
            name='phoneNumberOrdering',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='office',
            name='salePointId',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='office',
            name='showcaseId',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='office',
            name='subwayStation',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='office',
            name='tele2Store',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='office',
            name='title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='site',
            name='contextRoot',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='site',
            name='defaultLanguage',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='site',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='site',
            name='productionUrl',
            field=models.CharField(max_length=150),
        ),
    ]
