import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { UserProvider } from "@/hooks/user-context";
import { NotificationManagerProvider } from "@/hooks/notification-context";
import { GEOProvider } from "@/hooks/geo-context";
import Header from "./components/header/page";
import Notifications from "./components/notifications/page";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <GEOProvider>
      <UserProvider>
        <NotificationManagerProvider>
          <html lang="en">
            <body>
              <Header />
              <Notifications />
              {children}
            </body>
          </html>
        </NotificationManagerProvider>
      </UserProvider>
    </GEOProvider>
  );
}
